---
- name: "Remove ELK on localhost"
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: "stop elasticsearch service"
      ansible.builtin.service:
        name: elasticsearch
        state: stopped
    - name: "stop filebeat service"
      ansible.builtin.service:
        name: filebeat
        state: stopped
    - name: "stop kibana service"
      ansible.builtin.service:
        name: kibana
        state: stopped

    - name: "remove opendistro stack"
      ansible.builtin.yum:
        name: opendistro*
        state: removed
    - name: "remove filebeat"
      ansible.builtin.yum:
        name: filebeat
        state: removed
    - name: "remove metricbeat"
      ansible.builtin.yum:
        name: metricbeat
        state: removed
